### ISSUE TITLE
cannot get local project working

### ISSUE THREAD

**Issue by timlewejohann** [jondeuce/MATDaemon.jl#9] opened 2023-08-22 08:13 UTC
After the installation in Matlab with the jlcall.m script built in julia function calls and installed package calls are working. However calling my own functions inside a julia projects always yields a cryptic error message. For the moment I am trying this with the TestProject from the repository which is lied inside the current matlab directory together with the jlcall file.
The following Matlab code is used to call a function from the julia project:
```matlab
jlcall('TestProject.dot','project', 'C:\Users\<Username>\Documents\MATLAB\TestProject','modules', {'TestProject'},'restart',true,'debug',false)
```
Within the Test Project the only change is the exclusion of  StaticArrays:
```julia
module TestProject
#using StaticArrays

function dot(x)
    return 3+x
end

end # module
```

When activating and executing the project from the julia terminal everything works as expected.

However calling it from the Matlab script yields the following error message:
```matlab
[31m[1mERROR: [97;22mLoadError:[31;22m IOError: could not spawn setenv(`'C:\Users\<Username>\AppData\Local\Programs\Julia-1.9.2\libexec\julia\7z.exe' x 'C:\Users\<Username>\.julia\registries\General.tar.gz' -so`,["WINDIR=C:\\Windows", "PATH=C:\\Users\\<Username>\\AppData\\Local\\Programs\\Julia-1.9.2\\bin\\..\\lib\\julia;C:\\Users\\<Username>\\AppData\\Local\\Programs\\Julia-1.9.2\\bin\\..\\lib;C:\\Program Files\\MATLAB\\R2023a\\bin\\win64;C:\\Program Files\\Python39\\Scripts\\;C:\\Program Files\\Python39\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\MATLAB\\R2023a\\bin;C:\\Program Files\\Docker\\Docker\\resources\\bin;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Users\\<Username>\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\<Username>\\AppData\\Local\\Programs\\Git\\cmd;C:\\Users\\<Username>\\AppData\\Local\\Programs\\MiKTeX\\miktex\\bin\\x64\\;C:\\Users\\<Username>\\AppData\\Local\\Programs\\Julia-1.9.2\\bin", "USERDOMAIN_ROAMINGPROFILE=---", "ZES_ENABLE_SYSMAN=1", "LOCALAPPDATA=C:\\Users\\<Username>\\AppData\\Local", "HOMEPATH=\\Users\\<Username>", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 141 Stepping 1, GenuineIntel", "NUMBER_OF_PROCESSORS=16", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW", "SESSIONNAME=Console", "SYSTEMROOT=C:\\Windows", "APPDATA=C:\\Users\\<Username>\\AppData\\Roaming", "=::=::\\", "PSMODULEPATH=C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules", "COMMONPROGRAMW6432=C:\\Program Files\\Common Files", "PROGRAMDATA=C:\\ProgramData", "PROMPT=\$P\$G", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=---", "OS=Windows_NT", "PROCESSOR_REVISION=8d01", "ICU_TIMEZONE_FILES_DIR=C:\\Program Files\\MATLAB\\R2023a/bin/icutzdata", "TMP=C:\\Users\\<Username>\\AppData\\Local\\Temp", "COMMONPROGRAMFILES(X86)=C:\\Program Files (x86)\\Common Files", "COMSPEC=C:\\Windows\\system32\\cmd.exe", "KMP_HANDLE_SIGNALS=0", "OPENBLAS_DEFAULT_NUM_THREADS=1", "KMP_BLOCKTIME=1", "ALLUSERSPROFILE=C:\\ProgramData", "COMMONPROGRAMFILES=C:\\Program Files\\Common Files", "COMPUTERNAME=DPC0137", "MATDAEMON_WORKSPACE=C:\\Users\\<Username>\\Documents\\MATLAB\\.jlcall", "ONEDRIVE=C:\\Users\\<Username>\\OneDrive", "MATLAB_ARCH=win64", "USERNAME=<Username>", "PROGRAMFILES(X86)=C:\\Program Files (x86)", "PROGRAMFILES=C:\\Program Files", "KMP_STACKSIZE=512k", "LOGONSERVER=\\\\DEVDC1", "USERPROFILE=C:\\Users\\<Username>", "DRIVERDATA=C:\\Windows\\System32\\Drivers\\DriverData", "FPS_BROWSER_USER_PROFILE_STRING=Default", "PROCESSOR_LEVEL=6", "SYSTEMDRIVE=C:", "USERDNSDOMAIN=---.LOCAL", "=C:=C:\\Users\\<Username>\\Documents\\MATLAB", "FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer", "__KMP_REGISTERED_LIB_3764=00007FFD87C44D04-cafe2ab4-libiomp5md.dll", "PROGRAMW6432=C:\\Program Files", "TEMP=C:\\Users\\<Username>\\AppData\\Local\\Temp", "HOMEDRIVE=C:", "OPENBLAS_MAIN_FREE=1", "PROCESSOR_ARCHITECTURE=AMD64", "QT_QPA_PLATFORM=windows:fontengine=freetype"]): operation not supported on socket (ENOTSUP)[0m
Stacktrace:
 [1] [1m_spawn_primitive[0m at [1m.\process.jl:128[0m
 [2] [1m#760[0m at [1m.\process.jl:139[0m
 [3] [1msetup_stdios[0m at [1m.\process.jl:223[0m
 [4] [1m_spawn[0m at [1m.\process.jl:138[0m
 [5] [1m#open#769[0m at [1m.\process.jl:393[0m
 [6] [1mopen[0m at [1m.\process.jl:383[0m
 [7] [1m#open#770[0m at [1m.\process.jl:415[0m
 [8] [1mopen[0m at [1m.\process.jl:414[0m
 [9] [1muncompress_registry[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\Registry\registry_instance.jl:256[0m
 [10] [1mRegistryInstance[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\Registry\registry_instance.jl:323[0m
 [11] [1m#reachable_registries#25[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\Registry\registry_instance.jl:429[0m
 [12] [1mreachable_registries[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\Registry\registry_instance.jl:399[0m
 [13] [1mContext[0m at [1m.\util.jl:567[0m
 [14] [1m_activate_dep[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\API.jl:1799[0m [15] [1m#activate#296[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\API.jl:1822[0m
 [16] [1mactivate[0m at [1mC:\workdir\usr\share\julia\stdlib\v1.9\Pkg\src\API.jl:1812[0m
 [17] [1minit_environment[0m at [1mC:\Users\<Username>\.julia\packages\MATDaemon\UjPSQ\src\MATDaemon.jl:179[0m
 [18] [1mtop-level scope[0m at [1mC:\Users\<Username>\.julia\packages\MATDaemon\UjPSQ\api\jlcall.jl:14[0m
 [19] [1minclude[0m at [1m.\client.jl:478[0m
 [20] [1mtop-level scope[0m at [1mC:\Users\<Username>\Documents\MATLAB\.jlcall\tmp\0093_mat_tpa1669f30_3f4b_4d54_aa57_871144592938.jl:5[0m
 [21] [1meval[0m at [1m.\boot.jl:370[0m
```

**Comment by jondeuce** [comment] 2023-08-24 21:20
It looks like Julia is failing to activate the project [here](https://github.com/jondeuce/MATDaemon.jl/blob/6a1de76acd835991e24f07067dd8c43c59e5e380/src/MATDaemon.jl#L179). Are you sure you are passing the correct path to the project, and that the project is fully instantiated [as per the docs](https://github.com/jondeuce/MATDaemon.jl#loading-code-from-a-local-project)? E.g. I assume you have anonymized the above error message and did not actually pass `<Username>` in the project path, but are you able to start Julia in the `TestProject` directory and run `using TestProject`?

**Comment by pdetrempe** [comment] 2023-10-10 22:31
Hi there. I'm having the same issue. The following works:

`jlcall('TestProject.dot','project', 'C:\Users\<Username>\Documents\MATLAB\TestProject','modules', {'LinearAlgebra'},'restart',true,'debug',false)`

But the following fails:

`jlcall('TestProject.dot','project', 'C:\Users\<Username>\Documents\MATLAB\TestProject','modules', {'TestProject'},'restart',true,'debug',false)`

The latter gives the following error in the MATLAB window:
```
Error using jlcall>call_julia (line 417)
Julia call failed to produce the expected output
file:
C:\Users\<user>\AppData\Local\Temp\1\tp7befe025_d7d3_4df5_b7cc_144e7fd1cac6.mat

Error in jlcall (line 245)
    varargout = call_julia(f_args, opts);
```

I'm on Windows and Julia 1.9, if that helps.

**Comment by jondeuce** [comment] 2023-10-12 17:13
Unfortunately I don't have access to a Windows machine, and I can't reproduce the issue.

Could you try re-running with the `'debug'` flag set to `true`? It will print more diagnostic information.

Also, are you using MATLAB R2023b (the most recent version) by any chance? MATLAB recently made a change to their `system` command, which I use quite extensively, that seems to have broken some things here and I haven't figured out a fix yet.

**Comment by pdetrempe** [comment] 2023-10-12 18:05
Yup! Here's some more detailed output with `debug` set to `true`:

Here's the script I'm running and the MATLAB command window output:
![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/a6f9c52a-0df1-404d-9b22-eb2ad243b376)
![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/c710797b-6488-443e-b704-95b10390f144)

I tried dropping a debug just before the `cmd` call in [line 486](https://github.com/jondeuce/MATDaemon.jl/blob/364cd96dcf2dc44e834a7f119294d5b7831fe7f4/api/jlcall.m#L486) and executing the command in a separate window to get more debug output. Here's the result:

Breakpoint in MATLAB:
![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/7f9ee8c4-2ae6-4414-9912-92914a07a3d1)

Running the command script in Julia:
![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/5075bb80-2d8b-4201-b376-3e5365cbb33f)

This is on MATLAB 2018b with Julia 1.9.2.

**Comment by jondeuce** [comment] 2023-10-13 04:09
Based on that the last error message from the Julia console, it looks like a permissions issue from the Julia server: "operation not supported on socket (ENOTSUP)". I'm really not sure why that would be, though...

Can you try running it again with the `'server'` flag set to `false`, too? It will be slower, but hopefully easier to debug.

**Comment by pdetrempe** [comment] 2023-10-13 15:30
Ok so, I ran with `server` set to `false`, and I have some really interesting behavior to report. Changing server to `false` seems to have fixed the issue.

Not only did it fix the issue, but then running again with `server` set to `true` also worked.

![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/b856c69d-9091-4439-a958-87ed2067a80a)
![image](https://github.com/jondeuce/MATDaemon.jl/assets/24377991/ba4e2f97-5933-4b85-b7f0-816881125645)

Fortunately, this means `MATDaemon` is now working on my machine. Unfortunately, it means that I can no longer reproduce the error. Only thing to close this might be adding the `server` toggle as part of some troubleshooting documentation?

Thanks for all the help on this!

**Comment by jondeuce** [comment] 2023-10-13 18:04
Now that is surprising! I'll have to think about why this worked; in principle, the `'restart'` flag should have had a similar effect...

Thanks for your patience, I'll keep looking into this. And yes agreed, I will add a troubleshooting section to the docs.

**Comment by pdetrempe** [comment] 2023-10-14 01:11
Much appreciated for all the help on this!

**Comment by jondeuce** [comment] 2023-10-14 01:58
I've updated the README with some [troubleshooting tips](https://github.com/jondeuce/MATDaemon.jl#troubleshooting) and tagged a new MATDaemon with some quality of life improvements. In particular, Julia I/O is now printed into the MATLAB console (for example, error messages).

I recommend downloading the new [`jlcall.m`](https://github.com/jondeuce/MATDaemon.jl/blob/master/api/jlcall.m) when you get a chance (and be sure to delete the `.jlcall` workspace folder so that the new version gets installed)

**Comment by pdetrempe** [comment] 2023-10-16 23:37
Thanks! It's working well for me now. Just a heads up in case you're still interested in this error. I suspected that it was due to installed packages, so I managed to recreate it by adding `Cthulu.jl` to the `TestProject`, then running again without setting `server` to `false`.

Here's what I ran post-Cthulu install:

jlcall('LinearAlgebra.norm', {[3.0; 4.0]}, ...
    'project', 'C:\\Users\\pdetremp\\.julia\\dev\\MATDaemon\\test\\TestProject', ... % activate a local Julia Project
    'modules', {'LinearAlgebra', 'TestProject'},...  % load a custom module and some modules from Base Julia
    'threads', 'auto', ... % use the default number of Julia threads
    'restart', true,...
    'debug', true,...
    'server', true)


Resulting MATLAB output:

```

* Starting Julia server

* Ran `MATDaemon.start` script from Julia server (status = 0):
*   C:\Users\pdetremp\AppData\Local\Programs\Julia-1.9.2\bin\julia.exe --project=C:\Users\pdetremp\.julia\dev\MATDaemon\api\.jlcall --threads=auto --startup-file=no --quiet --optimize=3 C:\Users\pdetremp\.julia\dev\MATDaemon\api\.jlcall\tmp\0000_mat_tp5423fed1_7e75_40ae_91bb_7ffed60ca954.jl &
Warning: Escaped character '\e' is not valid. See 'doc sprintf' for
supported special characters. 
> In jlcall>try_run (line 514)
  In jlcall>call_julia (line 426)
  In jlcall (line 260)
  In script_test_MAT_Daemon (line 9) 
[31m[1mERROR: [97;22mLoadError:[31;22m MethodError: no method matching MATDaemon.JLCallOptions(; VERSION::String, shared::Bool, threads::Int64, quiet::Bool, setup::String, reinstall::Bool, gc::Bool, workspace::String, outfile::String, debug::Bool, cwd::String, project::String, infile::String, f::String, shutdown::Bool, port::Float64, nofun::Bool, modules::Vector{Any}, runtime::String, server::Bool, restart::Bool)[0m
Stacktrace:
 [1] [1mkwerr[0m at [1m.
* Sent `DaemonMode.runfile` script to Julia server (status = 0):
*   C:\Users\pdetremp\AppData\Local\Programs\Julia-1.9.2\bin\julia.exe --project=C:\Users\pdetremp\.julia\dev\MATDaemon\api\.jlcall --threads=auto --startup-file=no --quiet --optimize=0 --compile=min C:\Users\pdetremp\.julia\dev\MATDaemon\api\.jlcall\tmp\0002_mat_tpbb573d80_08d5_4b97_a562_504079af84a7.jl
Error using jlcall>call_julia (line 440)
Julia call failed to produce the expected output file:
C:\Users\pdetremp\AppData\Local\Temp\1\tpa8191bd3_f62b_4749_a9dc_04f4d9c1d84f.mat

Error in jlcall (line 260)
    varargout = call_julia(f_args, opts);

Error in script_test_MAT_Daemon (line 9)
jlcall('LinearAlgebra.norm', {[3.0; 4.0]}, ...
 ```
 
 Very nice to see the Julia output in the MATLAB window! Everything is working for my main project now. Just wanted to post to confirm that the error output is working with the new `jlcall.m` file.

**Comment by pdetrempe** [comment] 2023-10-16 23:45
Actually, after restarting MATLAB, I get the following error in my main project when running with the new `jlcall.m` function:
```
ERROR: LoadError: MethodError: no method matching MATDaemon.JLCallOptions(; VERSION::String, shared::Bool, threads::Int64, quiet::Bool, setup::String, reinstall::Bool, gc::Bool, workspace::String, outfile::String, debug::Bool, cwd::String, project::String, infile::String, f::String, shutdown::Bool, port::Float64, nofun::Bool, modules::Vector{Any}, runtime::String, server::Bool, restart::Bool)

Closest candidates are:
  MATDaemon.JLCallOptions(; f, infile, outfile, runtime, project, threads, setup, nofun, modules, cwd, workspace, server, port, shared, restart, shutdown, gc, debug) got unsupported keyword arguments "VERSION", "quiet", "reinstall"
   @ MATDaemon util.jl:567
  MATDaemon.JLCallOptions(!Matched::String, !Matched::String, !Matched::String, !Matched::String, !Matched::String, !Matched::Int64, !Matched::String, !Matched::Bool, !Matched::Vector{Any}, !Matched::String, !Matched::String, !Matched::Bool, !Matched::Int64, !Matched::Bool, !Matched::Bool, !Matched::Bool, !Matched::Bool, !Matched::Bool) got unsupported keyword arguments "VERSION", "shared", "threads", "quiet", "setup", "reinstall", "gc", "workspace", "outfile", "debug", "cwd", "project", "infile", "f", "shutdown", "port", "nofun", "modules", "runtime", "server", "restart"
   @ MATDaemon C:Error using jlcall>try_run (line 524)
Julia call failed (status = 1)

Error in jlcall>call_julia (line 429)
        try_run(opts, job_script, 'local', 'Called
        `MATDaemon.jlcall` from local Julia process');

Error in jlcall (line 260)
    varargout = call_julia(f_args, opts);

Error in script_test_MAT_Daemon (line 29)
jlcall('', ...
```

**Comment by jondeuce** [comment] 2023-10-16 23:58
Thanks for the update. These issues seem to be due to MATDaemon not being updated: `got unsupported keyword arguments "VERSION", "quiet", "reinstall"` - these flags were updated in `v0.1.3`.

If you manually update the packages in the `.jlcall` workspace folder (stored in the same folder as `jlcall.m`), it should work: `julia --project=.jlcall -e 'using Pkg; Pkg.update()'`. Normally, deleting and recreating the `.jlcall` folder using the `'reinstall'` flag should work, too, but if your Julia registry isn't updated then it may not actually install a newer version. I think I may add an `'update'` flag in the future which would force update the packages for you.

**Comment by pdetrempe** [comment] 2023-10-17 04:00
Thanks! Updating the `.jlcall` environment worked. I think the forced update to the `.jlcall` environment to accompany the `update MATDaemon` call makes sense.

**Closed as completed** 2023-12-16 22:56 UTC
